### ISSUE TITLE
Let Windows Users Know How to Symlink

### ISSUE THREAD

**Issue by twd3** [statamic/docs#7] opened 2019-10-23 19:45 UTC
I read it's a good idea to symlink the resources\dist folder during the alpha but the docs only showed a way that didn't work for Windows users. Add this and mark it "for Windows users":
mklink /D C:\path\to\your\app\public\vendor\statamic\cp C:\path\to\three-cms\resources\dist

**Comment by damcclean** [comment] 2020-01-03 17:51
I'd be happy to PR something in but not sure if it's still relevant because I can't find any documentation on it. Maybe the gents removed it when v3 was released to open beta.

**Comment by guido4000** [comment] 2020-03-28 14:45
I can not find any information about symlinking, too. But it is still relevant as the V3 beta repo does not work out of the box. 

You get a bunch of error messages when loading the control panel:
GET http://localhost:3000/vendor/statamic/cp/css/cp.css?v=3.0.0-beta.22 net::ERR_ABORTED 404

**Comment by damcclean** [comment] 2020-03-28 14:46
Hmm, what happens if you run `php artisan statamic:install` then try agan?

**Comment by guido4000** [comment] 2020-03-28 14:48
> what happens if you run php artisan statamic:install then try agan?

This does not solve it.

I just followed the approach described here: https://statamic.dev/quick-start

**Comment by damcclean** [comment] 2020-03-28 14:51
> > what happens if you run php artisan statamic:install then try agan?
> 
> This does not solve it.
> 
> I just followed the approach described here: https://statamic.dev/quick-start

Strange... What web server are you using, and is it pointing to Statamic's `public` directory?

It might be better to move this conversation to [Discord](https://statamic.com/discord) or an issue on [`statamic/cms`](https://github.com/statamic/cms/issues) instead of on the docs repo.

**Comment by guido4000** [comment] 2020-03-28 15:02
I run it through the CLI:

php -S localhost:3000 server.php

The homepage is working as intended. I just do not have a cp folder in the statatmic vendor directory or a symlink as described above.

**Comment by damcclean** [comment] 2020-03-28 15:08
OK, the vendor folder shouldn't be symlinked. It should have copied across the relevant files when you installed Statamic.

The files would be copied over from `vendor/statamic/cms/resources/dist` into `public/vendor/statamic/cp`. If you copy them across it should be OK. 

Still not entirely sure why it didn't do it at install time unless you're installing `master` or some other branch.

**Comment by guido4000** [comment] 2020-03-28 15:16
Yes, thank you for the feedback. 

As mentioned I just followed the few steps in the tutorial.

**Comment by duncanmcclean** [comment] 2021-03-12 17:23
Statamic v3 has been released and there's no longer a need to setup symlinks to use Statamic, you can download it with Composer.

Therefore, I'm closing this issue.

**Closed by duncanmcclean** 2021-03-12 17:23 UTC
